name: sr4zct
channels:
  - aahendriksen
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - aahendriksen::msd_pytorch=0.10.1
  - cudatoolkit=11.1
  - imageio
  - numpy
  - pip
  - pydicom=2.3.0
  - scikit-image=0.19.2
  - scipy=1.9.1
  - tqdm
  - pip:
    - pcfv==0.0.19
